# Generated by Django 5.2.8 on 2026-05-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samsara', '0004_samsaratrip_driver_start_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='samsaratrip',
            new_name='samsara_sam_driver__313761_idx',
            old_name='samsara_trip_drv_start_idx',
        ),
    ]
