# Generated by Django 5.2.8 on 2026-05-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samsara', '0006_samsaratripssyncstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samsaratripssyncstate',
            name='last_query_end_ms',
            field=models.BigIntegerField(blank=True, help_text='End of last successful trips API window (Unix ms).', null=True),
        ),
    ]
