# Generated by Django 5.2.8 on 2026-05-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samsara', '0008_samsaratrip_vehicle_start_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='samsaratrip',
            new_name='samsara_sam_vehicle_5d661c_idx',
            old_name='samsara_trip_veh_start_idx',
        ),
    ]
