# Generated by Django 5.2.8 on 2026-02-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_id', models.CharField(max_length=120, unique=True)),
                ('dept', models.CharField(blank=True, default='', max_length=20)),
                ('zone', models.CharField(blank=True, default='', max_length=20)),
                ('seat_no', models.CharField(blank=True, default='', max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
