# Generated by Django 5.2.8 on 2026-02-18 20:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop/PC'), ('MONITOR', 'Monitor'), ('HEADSET', 'Headset'), ('KEYBOARD', 'Keyboard'), ('MOUSE', 'Mouse'), ('DOCK', 'Dock/Hub'), ('PHONE', 'Phone'), ('OTHER', 'Other')], max_length=20)),
                ('brand', models.CharField(blank=True, default='', max_length=80)),
                ('model', models.CharField(blank=True, default='', max_length=80)),
                ('serial_number', models.CharField(blank=True, default='', max_length=80)),
                ('inventory_tag', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('IN_USE', 'In use'), ('IN_STOCK', 'In stock'), ('BROKEN', 'Broken'), ('LOST', 'Lost'), ('RETIRED', 'Retired')], default='IN_USE', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, default='', max_length=80)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.CharField(blank=True, default='', max_length=80)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='office.asset')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_assignments', to='office.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'end_at'], name='office_asse_employe_40d72d_idx'), models.Index(fields=['asset', 'end_at'], name='office_asse_asset_i_11d2e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_assignments', to='office.employee')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='office.seat')),
            ],
            options={
                'indexes': [models.Index(fields=['seat', 'end_at'], name='office_seat_seat_id_647bd0_idx'), models.Index(fields=['employee', 'end_at'], name='office_seat_employe_d80236_idx')],
            },
        ),
    ]
