# Generated by Django 5.2.8 on 2026-02-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_asset_employee_assetassignment_seatassignment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='seatassignment',
            name='office_seat_seat_id_647bd0_idx',
        ),
        migrations.RemoveIndex(
            model_name='seatassignment',
            name='office_seat_employe_d80236_idx',
        ),
        migrations.AddField(
            model_name='employee',
            name='company_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='employee',
            name='company_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('IN_USE', 'In use'), ('IN_STOCK', 'In stock'), ('BROKEN', 'Broken'), ('LOST', 'Lost'), ('RETIRED', 'Retired'), ('PRIVATE', 'Private')], default='IN_USE', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='seatassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_at__isnull', True)), fields=('seat',), name='uniq_active_seat_assignment_per_seat'),
        ),
    ]
