# Generated by Django 5.2.8 on 2026-02-19 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_remove_seatassignment_office_seat_seat_id_647bd0_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
    ]
