# Generated by Django 5.2.8 on 2026-05-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_officedirectoryemployee_officeequipmentitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeequipmentitem',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('in_service', 'In service'), ('broken', 'Broken'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='draft', max_length=20),
        ),
    ]
