# Generated by Django 5.2.8 on 2026-05-04 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_department_model_and_employee_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officedirectoryemployee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='office.department'),
        ),
    ]
