# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0010_alter_officedirectoryemployee_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="officedirectoryemployee",
            name="location",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="officedirectoryemployee",
            name="position",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
