# Generated by Django 5.2

from django.db import migrations, models


def copy_email_phone_to_work(apps, schema_editor):
    Employee = apps.get_model("office", "OfficeDirectoryEmployee")
    for row in Employee.objects.all().iterator(chunk_size=500):
        updates = {}
        if getattr(row, "email", None):
            updates["work_email"] = row.email
        if getattr(row, "phone", None):
            updates["work_phone"] = row.phone
        if updates:
            Employee.objects.filter(pk=row.pk).update(**updates)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0011_officedirectoryemployee_location_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="officedirectoryemployee",
            name="work_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="officedirectoryemployee",
            name="private_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="officedirectoryemployee",
            name="work_phone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="officedirectoryemployee",
            name="private_phone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.RunPython(copy_email_phone_to_work, noop_reverse),
        migrations.RemoveField(
            model_name="officedirectoryemployee",
            name="email",
        ),
        migrations.RemoveField(
            model_name="officedirectoryemployee",
            name="phone",
        ),
    ]
