# Generated by Django 5.2.8 on 2026-05-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dispatchdriver',
            new_name='dispatch_di_dispatc_43f878_idx',
            old_name='dispatch_di_dispat_0f7c8e_idx',
        ),
    ]
