# Generated by Django 5.2.8 on 2026-05-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_dispatchdriver_dispatcher_optional'),
        ('dispatch', '0002_rename_dispatch_di_dispat_0f7c8e_idx_dispatch_di_dispatc_43f878_idx'),
    ]

    operations = [
    ]
