# Generated by Django 5.2.8 on 2026-05-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_merge_20260512_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatchdriver',
            options={'ordering': ['sort_order', 'last_name', 'first_name']},
        ),
    ]
