# Generated by Django 5.2.8 on 2026-05-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_dispatchtruck_trailer_driver_optional'),
        ('dispatch', '0004_alter_dispatchdriver_options'),
    ]

    operations = [
    ]
