# Generated by Django 5.2.8 on 2026-05-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0005_merge_20260512_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatchtrailer',
            options={'ordering': ['unit_number']},
        ),
    ]
