# Generated by Django 5.2.8 on 2026-05-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0007_dispatchtrip_dispatchtripload'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dispatchtripload',
            new_name='dispatch_di_trip_id_728d5c_idx',
            old_name='dispatch_tripload_trip_seq_idx',
        ),
    ]
