# Generated by Django 5.2.8 on 2026-05-12 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0008_dispatchtrip_planner_date'),
        ('dispatch', '0008_rename_dispatch_tripload_trip_seq_idx_dispatch_di_trip_id_728d5c_idx'),
    ]

    operations = [
    ]
