# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch", "0011_dispatchdriver_extended_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchdriver",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Driver cell or primary phone (optional).",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="dispatchdriver",
            name="email",
            field=models.EmailField(blank=True, help_text="Driver email (optional).", max_length=254),
        ),
        migrations.AddField(
            model_name="dispatchdriver",
            name="rts_fuel_card",
            field=models.BooleanField(
                default=False,
                help_text="Whether the driver has an RTS fuel card.",
            ),
        ),
        migrations.AddField(
            model_name="dispatchdriver",
            name="notes",
            field=models.TextField(blank=True, help_text="Internal notes for dispatch."),
        ),
    ]
