# Generated by Django 5.2.8 on 2026-05-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0012_dispatchdriver_contact_rts_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchdriver',
            name='fleet_company',
            field=models.CharField(blank=True, choices=[('fully_triumph', 'FULLY TRIUMPH'), ('fully_ilim', 'FULLY ILIM'), ('fully_gns', 'FULLY GNS'), ('triumph_ilim', 'TRIUMPH/ILIM'), ('triumph_ferrum', 'TRIUMPH/FERRUM'), ('gns_ferrum', 'GNS/FERRUM'), ('gns_ilim', 'GNS/ILIM'), ('ilim_ferrum', 'ILIM/FERRUM')], help_text='Operating company (dropdown).', max_length=32),
        ),
    ]
