# Generated by Django 5.2.8 on 2026-05-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0014_dispatchassignment_remove_equipment_driver'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dispatchassignment',
            new_name='dispatch_di_driver__dbeed5_idx',
            old_name='dispatch_di_driver__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='dispatchassignment',
            new_name='dispatch_di_truck_i_b653df_idx',
            old_name='dispatch_di_truck_i_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='dispatchassignment',
            new_name='dispatch_di_trailer_c194dd_idx',
            old_name='dispatch_di_trailer_g7h8i9_idx',
        ),
    ]
