# Generated by Django 5.2.8 on 2026-05-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0019_dispatchtripload_pickup_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchtripload',
            name='pickup_datetime',
            field=models.DateTimeField(blank=True, help_text='Scheduled pick-up date and time for this load.', null=True),
        ),
    ]
