# Generated by Django 5.2.8 on 2026-05-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0020_alter_dispatchtripload_pickup_datetime'),
        ('dispatch', '0022_dispatchtripload_status'),
    ]

    operations = [
    ]
