# Generated by Django 5.2.8 on 2026-05-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0024_dispatchtripstatushistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dispatchtripstatushistory',
            new_name='dispatch_di_trip_id_cd7257_idx',
            old_name='dispatch_di_trip_id_0a8f2e_idx',
        ),
    ]
