# Generated by Django 5.2.8 on 2026-05-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0026_dispatchtriploadstatushistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dispatchtriploadstatushistory',
            new_name='dispatch_di_load_id_1484c4_idx',
            old_name='dispatch_di_load_id_7c4a91_idx',
        ),
    ]
