# Generated by Django 5.2.8 on 2026-05-19 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0028_remove_trips_loads_only'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dispatchload',
            new_name='dispatch_di_driver__055924_idx',
            old_name='dispatch_di_driver__loads_idx',
        ),
        migrations.RenameIndex(
            model_name='dispatchloadstatushistory',
            new_name='dispatch_di_load_id_38f5f4_idx',
            old_name='dispatch_di_load_id_1484c4_idx',
        ),
    ]
