# Generated by Django 5.2.8 on 2026-05-19 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0029_rename_dispatch_di_driver__loads_idx_dispatch_di_driver__055924_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchload',
            name='planner_date',
            field=models.DateField(blank=True, db_index=True, help_text='Planner grid day (delivery day) for the assigned driver.', null=True),
        ),
        migrations.CreateModel(
            name='DriverUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('vacation', 'Vacation / time off'), ('sick', 'Sick'), ('cannot_drive', 'Cannot drive'), ('other', 'Other')], default='vacation', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailability_entries', to='dispatch.dispatchdriver')),
            ],
            options={
                'verbose_name_plural': 'driver unavailability entries',
                'ordering': ['-start_date', '-pk'],
                'indexes': [models.Index(fields=['driver', 'start_date', 'end_date'], name='dispatch_dr_driver__8a57a9_idx')],
            },
        ),
    ]
