# Generated by Django 5.2.8 on 2026-05-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0031_dispatchloadcomment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dispatchloadcomment',
            new_name='dispatch_di_load_id_aa382b_idx',
            old_name='dispatch_di_load_id_cmt_idx',
        ),
    ]
