# Generated by Django 5.2.8 on 2026-05-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0032_rename_dispatch_di_load_id_cmt_idx_dispatch_di_load_id_aa382b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchload',
            name='pod_status',
            field=models.CharField(choices=[('not_sent', 'Not sent'), ('sent', 'Sent'), ('not_delivered', 'Not delivered'), ('delivered', 'Delivered')], db_index=True, default='not_sent', help_text='Proof of delivery: sent, not sent, not delivered, or delivered.', max_length=32, verbose_name='POD status'),
        ),
        migrations.AddField(
            model_name='dispatchload',
            name='rc_status',
            field=models.CharField(choices=[('not_sent', 'Not sent'), ('sent', 'Sent'), ('uploaded', 'Uploaded')], db_index=True, default='not_sent', help_text='Rate confirmation: sent, not sent, or uploaded.', max_length=32, verbose_name='RC status'),
        ),
    ]
