# Generated by Django 5.2.8 on 2025-11-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('gallons', models.FloatField()),
                ('amount_paid', models.FloatField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fuel Record',
                'verbose_name_plural': 'Fuel Records',
                'ordering': ['vehicle', 'date'],
            },
        ),
        migrations.CreateModel(
            name='IftaSamsara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=100)),
                ('jurisdiction', models.CharField(max_length=10)),
                ('taxable_miles', models.FloatField()),
                ('total_miles', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IFTA (Samsara)',
                'verbose_name_plural': 'IFTA (Samsara)',
                'ordering': ['vehicle', 'jurisdiction'],
            },
        ),
    ]
