# Generated by Django 5.2.8 on 2025-11-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iftasamsara',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='iftasamsara',
            name='tax_paid_gallons',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iftasamsara',
            name='vehicle',
            field=models.CharField(max_length=50),
        ),
    ]
