# Generated by Django 5.2.8 on 2025-11-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_add_canada_provinces'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_date', models.DateField()),
                ('unit', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=10)),
                ('item', models.CharField(max_length=50)),
                ('qty', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fuel Transaction',
                'verbose_name_plural': 'Fuel Transactions',
                'ordering': ['unit', 'tran_date'],
            },
        ),
        migrations.DeleteModel(
            name='FuelRecord',
        ),
    ]
