# Generated by Django 5.2.8 on 2025-11-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_vehiclerecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FuelTransaction',
        ),
        migrations.AddField(
            model_name='vehiclerecord',
            name='file_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='IftaSamsara',
        ),
    ]
