# Generated by Django 5.2.8 on 2026-04-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_delete_fueltransaction_vehiclerecord_file_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee_id", models.CharField(blank=True, max_length=12, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("login_type", models.CharField(choices=[("company", "Company"), ("native", "Native"), ("contractor", "Contractor"), ("other", "Other")], default="company", max_length=20)),
                ("department", models.CharField(choices=[("tracking", "Tracking"), ("hr", "HR"), ("it", "IT"), ("safety", "Safety"), ("dispatch", "Dispatch"), ("recruiter", "Recruiter"), ("finance", "Finance")], default="it", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("asset_id", models.CharField(max_length=40, unique=True)),
                ("equipment_type", models.CharField(choices=[("computer", "Computer"), ("monitor", "Monitor"), ("laptop", "Laptop"), ("printer", "Printer"), ("router", "Router"), ("tv", "Television"), ("other", "Other")], default="computer", max_length=20)),
                ("brand_model", models.CharField(blank=True, max_length=140)),
                ("serial_number", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("assigned_employee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="equipment_items", to="app.employee")),
            ],
            options={
                "ordering": ["asset_id"],
            },
        ),
    ]
