# Generated by Django 5.2.8 on 2026-04-29
# Database: no-op — do not drop app_employee / app_equipmentitem (owned by office).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_employee_equipmentitem"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="equipmentitem",
                    name="assigned_employee",
                ),
                migrations.DeleteModel(
                    name="Employee",
                ),
                migrations.DeleteModel(
                    name="EquipmentItem",
                ),
            ],
            database_operations=[],
        ),
    ]
