# Generated by Django 5.2.8 on 2026-04-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_employee_equipmentitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentitem',
            name='assigned_employee',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='EquipmentItem',
        ),
    ]
