# Generated by Django 5.2.8 on 2025-12-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyDriverData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_pay_percent', models.CharField(blank=True, max_length=10, null=True)),
                ('fuel', models.CharField(blank=True, max_length=50, null=True)),
                ('tolls', models.CharField(blank=True, max_length=50, null=True)),
                ('ifta', models.CharField(blank=True, max_length=50, null=True)),
                ('dispatch_factoring', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance', models.CharField(blank=True, max_length=50, null=True)),
                ('truck_trailer', models.CharField(blank=True, max_length=50, null=True)),
                ('admin', models.CharField(blank=True, max_length=50, null=True)),
                ('empty_col', models.CharField(blank=True, max_length=50, null=True)),
                ('driver', models.CharField(blank=True, max_length=100, null=True)),
                ('dispatch', models.CharField(blank=True, max_length=100, null=True)),
                ('miles', models.CharField(blank=True, max_length=50, null=True)),
                ('avg', models.CharField(blank=True, max_length=50, null=True)),
                ('gross', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_gross', models.CharField(blank=True, max_length=50, null=True)),
                ('cut', models.CharField(blank=True, max_length=50, null=True)),
                ('salary', models.CharField(blank=True, max_length=50, null=True)),
                ('truck', models.CharField(blank=True, max_length=50, null=True)),
                ('profit_loss', models.CharField(blank=True, max_length=50, null=True)),
                ('mpg', models.CharField(blank=True, max_length=50, null=True)),
                ('idle_time', models.CharField(blank=True, max_length=50, null=True)),
                ('idle_percent', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
