# Generated by Django 5.2.8 on 2025-12-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monday_cut', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monday_miles', models.IntegerField(default=0)),
                ('monday_rate_per_mile', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('tuesday_gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tuesday_cut', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tuesday_miles', models.IntegerField(default=0)),
                ('tuesday_rate_per_mile', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('wednesday_gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('wednesday_cut', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('wednesday_miles', models.IntegerField(default=0)),
                ('wednesday_rate_per_mile', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('thursday_gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('thursday_cut', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('thursday_miles', models.IntegerField(default=0)),
                ('thursday_rate_per_mile', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('friday_gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('friday_cut', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('friday_miles', models.IntegerField(default=0)),
                ('friday_rate_per_mile', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('saturday_gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('saturday_cut', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('saturday_miles', models.IntegerField(default=0)),
                ('saturday_rate_per_mile', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('sunday_gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sunday_cut', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sunday_miles', models.IntegerField(default=0)),
                ('sunday_rate_per_mile', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_cut', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_miles', models.IntegerField(default=0)),
                ('total_rate_per_mile', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
    ]
