# Generated by Django 5.2.8 on 2025-12-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_weeklysheet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklySheet',
        ),
    ]
