# Generated by Django 5.2.8 on 2025-12-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_delete_weeklysheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyDayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=10, unique=True)),
                ('gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cut', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('miles', models.IntegerField(default=0)),
                ('rate_per_mile', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
    ]
