# Generated by Django 5.2.8 on 2026-01-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0004_weeklydaydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTrucksFinalGross',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
                ('global_value', models.CharField(blank=True, default='', max_length=255)),
                ('unit_value', models.CharField(blank=True, default='', max_length=255)),
                ('count_value', models.CharField(blank=True, default='', max_length=255)),
                ('manager', models.CharField(blank=True, default='', max_length=255)),
                ('last_update', models.CharField(blank=True, default='', max_length=255)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AlterField(
            model_name='weeklydaydata',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday'), ('TOTALS', 'Totals')], max_length=10, unique=True),
        ),
    ]
