# Generated by Django 5.2.8 on 2026-01-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0005_activetrucksfinalgross_alter_weeklydaydata_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Npr: Active Trucks – Final Gross', max_length=255)),
                ('code', models.SlugField(help_text='Npr: ACTIVE_TRUCKS_FINAL_GROSS', max_length=100, unique=True)),
                ('sheet_id', models.CharField(help_text='Google Sheet ID ili putanja do Excel fajla', max_length=255)),
                ('sheet_range', models.CharField(help_text='Npr: N113:R121', max_length=50)),
                ('tab_name', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_interval_minutes', models.PositiveIntegerField(default=2, help_text='Koliko često se radi sync (u minutima)')),
                ('target_model', models.CharField(blank=True, help_text='Npr: statistic.ActiveTrucksFinalGross', max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='activetrucksfinalgross',
            options={'ordering': ['id']},
        ),
    ]
