# Generated by Django 5.2.8 on 2026-03-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0006_sheetconfig_alter_activetrucksfinalgross_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatcherSheetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatcher', models.CharField(blank=True, default='', max_length=200)),
                ('gross', models.CharField(blank=True, default='', max_length=50)),
                ('cut', models.CharField(blank=True, default='', max_length=50)),
                ('miles', models.CharField(blank=True, default='', max_length=50)),
                ('rpm', models.CharField(blank=True, default='', max_length=50)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
