# Generated by Django 5.2.8 on 2026-03-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0007_dispatchersheetrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchersheetrow',
            name='gpu',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
