# Generated by Django 5.2.8 on 2026-04-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0008_dispatchersheetrow_gpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchersheetrow',
            name='drpm',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
