# Generated by Django 5.2.8 on 2026-04-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0009_dispatchersheetrow_drpm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveTrucksFinalGross',
        ),
        migrations.DeleteModel(
            name='WeeklyDriverData',
        ),
        migrations.AlterField(
            model_name='sheetconfig',
            name='target_model',
            field=models.CharField(blank=True, help_text='Npr: statistic.DispatcherSheetRow', max_length=255),
        ),
    ]
