# Generated by Django 5.2.8 on 2025-11-15 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_created_at_iftasamsara_uploaded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='iftasamsara',
            options={'ordering': ['vehicle', 'state']},
        ),
        migrations.RemoveField(
            model_name='iftasamsara',
            name='jurisdiction',
        ),
        migrations.AddField(
            model_name='iftasamsara',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.state'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StateTaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(default='diesel', max_length=20)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state')),
            ],
            options={
                'ordering': ['state', 'valid_from'],
            },
        ),
    ]
