# Generated by Django 5.2.8 on 2025-11-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_fueltransaction_delete_fuelrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=100)),
                ('jurisdiction', models.CharField(max_length=10)),
                ('total_miles', models.FloatField(blank=True, null=True)),
                ('fuel_qty', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehicle Record',
                'verbose_name_plural': 'Vehicle Records',
                'ordering': ['vehicle', 'jurisdiction'],
                'unique_together': {('vehicle', 'jurisdiction')},
            },
        ),
    ]
